services:
  postgres:
    image: "postgres:16"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  mysql:
    image: "mysql:8.0"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"

  memcached:
    image: "memcached:1.6"
    ports:
      - "11211:11211"

  app:
    depends_on:
      - "postgres"
      - "mysql"
      - "redis"
      - "memcached"
    build: .
    command: bash -c "rm -f /usr/src/app/tmp/pids/server.pid && (bundle check || bundle install) && bundle exec rails s -b 0.0.0.0"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gems:/gems
    environment:
      - TEST_DATABASE_HOST=postgres

volumes:
  postgres:
  mysql:
  gems:
